const types = {
  ADD_NUMBER: "ADD_NUMBER",
  EDIT_NUMBER: "EDIT_NUMBER",
  CLEAR: 'CLEAR',
  ADD_OPERATION: 'ADD_OPERATION',
  ADD_DECIMAL: 'ADD_DECIMAL',
  CALCULATE: 'CALCULATE'
}

export default types;